version: "3.7"

services:
  bot:
    build: aida
    secrets: 
      - bot_token
    working_dir: /code
    volumes:
      - aida:/code/results
    restart: always
  
  gpt-2:
    build: gpt-2
    working_dir: /code
    volumes:
      - aida:/code/results
    restart: always

  stylegan:
    build: stylegan
    working_dir: /code
    volumes:
      - aida:/code/results
    restart: always

volumes: 
  aida:
secrets:
  bot_token: 
    file: token.txt