version: "2.4" #"3.7"

services:
  bot:
    build: aida
    secrets: 
      - bot_token
    working_dir: /code
    restart: always
    tty: true
    environment:
      - MY_CHANNEL=@aida_enelpi
    mem_limit: 30m
  
  gpt-2:
    build: gpt-2
    working_dir: /code
    restart: always
    tty: true
    mem_limit: 1g #980m #set to fit your machine
    memswap_limit: 4g #set to fit your machine
    

  stylegan:
    build: stylegan
    working_dir: /code
    restart: always
    tty: true
    environment: 
      - MODEL=network-snapshot-011170.pkl
    mem_limit: 500m #960m #set to fit your machine
    memswap_limit: 4g #set to fit your machine

  redis:
    image: redis:alpine3.13
    mem_limit: 10m
    restart: always

secrets:
  bot_token: 
    file: token.txt