version: "3.7"

services:
  bot:
    build: aida
    secrets: 
      - bot_token
    ports:
      - 3000:3000
    working_dir: /code
    volumes:
      - aida:/code/results
    restart: always
  
  gpt-2:
    build: gpt-2
    ports:
      - 3001:3001
    working_dir: /code
    volumes:
      - aida:/code/results
    restart: always

  stylegan:
    build: stylegan
    ports:
      - 3002:3002
    working_dir: /code
    volumes:
      - aida:/code/results
    restart: always

volumes: 
  aida:
secrets:
  bot_token: 
    file: token.txt